title: Arianna Masciolini
author: 
  name: Arianna Masciolini
  email: harisont@fripost.org

description: > 
  Arianna Masciolini/harisont's permanently-under-construction personal website and chaotically multilingual blog

show_excerpts: false

remote_theme: "jekyll/minima@1e8a445"

header_pages:
  - research.md
  - teaching.md
  - sw.md
  - photo.md
  - blog.md
  - lists.md

minima:
  skin: dark
  date_format: "%-d %B %Y"
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/harisont"
    - title: Mastodon
      icon: mastodon
      url: "https://mstdn.social/@harisont"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-include