title: Arianna Masciolini
author: 
  name: Arianna Masciolini
  email: arianna.masciolini@gmail.com

description: > 
  harisont's personal website and chaotically multilingual blog.

header_pages:
  - research.md
  - projects.md
  - blog.md
  - for_a_selected_few.md

show_excerpts: false

remote_theme: jekyll/minima

minima:
  skin: dark
  date_format: "%-d %B %Y"
  social_links:
    - { platform: github, user_url: https://github.com/harisont }
    - { platform: stackoverflow, user_url: https://stackoverflow.com/users/7729724/harisont }
    - { platform: instagram, user_url: https://www.instagram.com/unottica/ }
    - { platform: youtube, user_url: https://www.youtube.com/c/ImparalHaskellemettilodaparte }
    - { platform: rss, user_url: https://harisont.github.io/feed.xml}

plugins:
  - jekyll-feed